[package]
name = "easy-parallel"
version = "1.0.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Easy parallel closures"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/easy-parallel"
homepage = "https://github.com/stjepang/easy-parallel"
documentation = "https://docs.rs/easy-parallel"
keywords = ["scope", "thread", "scoped", "spawn"]
categories = ["concurrency"]
readme = "README.md"
